package com.chauhraj.kdb;

/**
 * Used to indicate there was an error generated by the remote process during the processing of a sync message or if the connection failed due to access credentials.
 * Network errors are reported as IOException.
 */
public class KException extends Exception {
  private static final long serialVersionUID = 1554689726734674152L; // autogenerated by serialver kx.c.KException

  /**
   * Constructs a new KException with the specified detail message.
   * @param s the detail message
   */
  public KException(String s) {
    super(s);
  }
} 